### ISSUE TITLE
KafkaHelper threading issue

### ISSUE THREAD

**Issue by eceejcr** [charithe/kafka-junit#45]
Hi there,

When using KafkaHelper consume methods I can see exceptions like this ocasionally:

Suppressed: java.util.ConcurrentModificationException: KafkaConsumer is not safe for multi-threaded access
		at org.apache.kafka.clients.consumer.KafkaConsumer.acquire(KafkaConsumer.java:1808)
		at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1701)
		at org.apache.kafka.clients.consumer.KafkaConsumer.close(KafkaConsumer.java:1680)

I see that consume methods take as input a kafkaconsumer instance and try to consume a given number of records using a different thread. But I think this not OK, because the org.apache.kafka.clients.consumer.kafkaConsumer class is documented as not thread safe. In fact, the kafkaConsumer looks able to detect this bad use of the API and throws the previous exception.

I guess that a possible approach could be to offer methods that take as input consumer configuration and that consumer is created kafka consumer in the same thread that consumption is done. The methods could return Futures.

I am currently using kafka-junit 4.0.0 with kafka-client 1.0., but I have been checking the latest release and I think it has the same problem.

Thanks in advance,

/Evaristo

**Comment by charithe** [comment]
The reason that some KafkaHelper methods take a consumer as a parameter is because there are many different configurations that can be applied when creating a consumer and accommodating all of them is quite hard to do without creating a very complicated API. The expectation is that the user is fully aware of the implications of using these helper methods (thread safety being an obvious issue to look out for).

I kind of regret the decision to create KafkaHelper. It was meant to help with quick and dirty testing scenarios so that people could get started quickly. For any serious testing code, I would strongly recommend just using the test broker and writing your own consumer logic.

**Comment by eceejcr** [comment]
Thx for the fast reply and the explanations about KafkaHelper goals. I will close the issue if that is OK for you.

**Comment by charithe** [comment]
Sure, go ahead :-)
