### ISSUE TITLE
Use Scala version 2.11

### ISSUE THREAD

**Issue by espenkm** [charithe/kafka-junit#8]
kafka-junit is compiled for org.apache.kafka_2.10:0.8.2.1 

I would like a version that is compiled with scala 2.11 instead as the 2.10 version does not work when the rest of my project uses 2.11. 

Tried to play around with mvn profiles to get this to work, but mvn isn`t by strongest side to say the least.

Any chance of getting a version compiled for 2.11 or maybe compile 1.6 for 2.11?

**Comment by charithe** [comment]
Interesting. May I ask what the exact nature of your build problem is? Although I haven't tried this library in Scala, in the past I have had no problems mixing Scala 2.10 and 2.11 dependencies. That leads me to believe that the problem is probably due to a clash between the Scala runtime bundled with Kafka and your project's runtime. 

I'll see if we can upgrade to the 2.11 Kafka anyway. But that might not yet be possible.

**Comment by espenkm** [comment]
Hi,

I checked our decencies and I have no dependencies to Scala 2.10 as far as
I could find (only 2.11). The code works fine if I just copy the
KafkaJunitRule class into my code and compile everything with
kafka_2.11-0.8.2.1

It seems that sending to Kafka just blocks. I can try to reproduce it with
a simple project if you are not able to go to 2.11

**Comment by charithe** [comment]
Ah, what I meant was that perhaps the Kafka dependency was pulling in Scala 2.10 runtime -- which could clash with the 2.11 runtime you have in your project.

Anyway, I don't see a reason why I can't just use the 2.11 build of Kafka. All tests pass with that version too. 

If you grab version 1.6 of kafka-junit from Maven Central, it will have the Kafka 2.11 dependencies. Hope that helps.

**Comment by espenkm** [comment]
That work just fine. Thanks a lot
